# Generated by Django 5.2.4 on 2025-07-16 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comicon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autore',
            name='opera_principale',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='autore_opera', to='comicon.fumetto'),
        ),
        migrations.AlterField(
            model_name='fumetto',
            name='casa_editrice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fumetti', to='comicon.casaeditrice'),
        ),
        migrations.AlterField(
            model_name='prodotto',
            name='casa_editrice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prodotti', to='comicon.casaeditrice'),
        ),
    ]
