# Generated by Django 5.2.4 on 2025-07-16 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comicon', '0002_alter_autore_opera_principale_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disponibilità',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('ora_inizio', models.TimeField()),
                ('ora_fine', models.TimeField()),
                ('autore', models.ForeignKey(limit_choices_to={'ruolo': 'autore'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('ora_inizio', models.TimeField()),
                ('ora_fine', models.TimeField()),
                ('stand', models.CharField(max_length=50)),
                ('posti_totali', models.PositiveIntegerField()),
                ('autore', models.ForeignKey(limit_choices_to={'ruolo': 'autore'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('casa_editrice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comicon.casaeditrice')),
            ],
        ),
        migrations.CreateModel(
            name='ProdottoEditore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=100)),
                ('prezzo', models.DecimalField(decimal_places=2, max_digits=6)),
                ('casa_editrice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comicon.casaeditrice')),
            ],
        ),
        migrations.CreateModel(
            name='RegistrazioneEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrazioni', to='comicon.evento')),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('evento', 'utente')},
            },
        ),
    ]
