# Generated by Django 5.2.4 on 2025-07-16 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comicon', '0003_disponibilità_evento_prodottoeditore_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utente',
            name='casa_editrice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comicon.casaeditrice'),
        ),
        migrations.AlterField(
            model_name='casaeditrice',
            name='nome',
            field=models.CharField(max_length=255),
        ),
    ]
