# Generated by Django 5.2.4 on 2025-07-17 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comicon', '0004_utente_casa_editrice_alter_casaeditrice_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='autore',
            name='casa_editrice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comicon.casaeditrice'),
        ),
        migrations.AddField(
            model_name='autore',
            name='genere',
            field=models.CharField(default='Non specificato', max_length=50),
        ),
        migrations.AddField(
            model_name='autore',
            name='giorni_disponibili',
            field=models.CharField(choices=[('23', '23'), ('24', '24'), ('25', '25'), ('26', '26')], default='23', max_length=2),
        ),
        migrations.AddField(
            model_name='autore',
            name='orari_disponibili',
            field=models.CharField(choices=[('11:30-13:30', '11:30-13:30'), ('14:00-16:00', '14:00-16:00'), ('16:30-18:30', '16:30-18:30')], default='11:30-13:30', max_length=20),
        ),
        migrations.AddField(
            model_name='stand',
            name='autore',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stand', to='comicon.autore'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='autore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comicon.autore'),
        ),
        migrations.CreateModel(
            name='Disponibilita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('ora_inizio', models.TimeField()),
                ('ora_fine', models.TimeField()),
                ('autore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comicon.autore')),
            ],
        ),
        migrations.DeleteModel(
            name='Disponibilità',
        ),
    ]
