# Generated by Django 5.2.4 on 2025-07-17 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comicon', '0005_genere_autore_casa_editrice_autore_genere_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autore',
            name='opera_principale',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='autore_opera', to='comicon.fumetto'),
        ),
    ]
