# Generated by Django 5.2.4 on 2025-07-17 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comicon', '0006_alter_autore_opera_principale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utente',
            name='ruolo',
            field=models.CharField(choices=[('utente', 'Utente'), ('autore', 'Autore'), ('editore', 'Casa Editrice'), ('admin', 'Amministratore')], default='utente', max_length=10),
        ),
    ]
