# Generated by Django 5.2.4 on 2025-07-17 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comicon', '0007_alter_utente_ruolo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autore',
            name='genere',
        ),
    ]
