# Generated by Django 5.2.4 on 2025-07-17 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comicon', '0008_remove_autore_genere'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disponibilita',
            name='ora_fine',
        ),
        migrations.RemoveField(
            model_name='disponibilita',
            name='ora_inizio',
        ),
        migrations.AddField(
            model_name='disponibilita',
            name='orario',
            field=models.CharField(default='11:30-13:30', max_length=20),
        ),
        migrations.AlterField(
            model_name='autore',
            name='giorni_disponibili',
            field=models.CharField(choices=[('2026-04-23', '2026-04-23'), ('2026-04-24', '2026-04-24'), ('2026-04-25', '2026-04-25'), ('2026-04-26', '2026-04-26')], default='2026-04-23', max_length=10),
        ),
    ]
