# Generated by Django 5.2.4 on 2025-07-17 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comicon', '0009_remove_disponibilita_ora_fine_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='data',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='ora_fine',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='ora_inizio',
        ),
        migrations.AddField(
            model_name='evento',
            name='disponibilita',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='comicon.disponibilita'),
        ),
    ]
