# Generated by Django 5.2.4 on 2025-07-17 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comicon', '0010_remove_evento_data_remove_evento_ora_fine_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stand',
            name='autore',
        ),
        migrations.AddField(
            model_name='stand',
            name='stallo',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6')], default=1),
        ),
        migrations.AddField(
            model_name='stand',
            name='totale_persone',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='stand',
            name='padiglione',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6')]),
        ),
    ]
