# Generated by Django 5.2.4 on 2025-07-17 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comicon', '0011_remove_stand_autore_stand_stallo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='posti_totali',
        ),
        migrations.AlterField(
            model_name='evento',
            name='stand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comicon.stand'),
        ),
    ]
