# Generated by Django 5.2.4 on 2025-07-18 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comicon', '0012_remove_evento_posti_totali_alter_evento_stand'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='ora',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='posti_disponibili',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
