# Generated by Django 5.2.4 on 2025-07-18 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comicon', '0013_evento_data_evento_ora_evento_posti_disponibili'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmacopie',
            name='casa_editrice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comicon.casaeditrice'),
        ),
        migrations.AddField(
            model_name='firmacopie',
            name='disponibilita',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='comicon.disponibilita'),
        ),
        migrations.AlterField(
            model_name='firmacopie',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='firmacopie',
            name='ora',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='firmacopie',
            name='posti_disponibili',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
