# Generated by Django 5.2.4 on 2025-07-18 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comicon', '0014_firmacopie_casa_editrice_firmacopie_disponibilita_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prenotazione',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comicon.evento'),
        ),
        migrations.AlterField(
            model_name='registrazioneevento',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrazioni', to='comicon.firmacopie'),
        ),
    ]
