# Generated by Django 5.2.4 on 2025-07-18 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comicon', '0015_alter_prenotazione_evento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prenotazione',
            name='evento',
        ),
        migrations.AddField(
            model_name='prenotazione',
            name='firmacopie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='comicon.firmacopie'),
        ),
    ]
