# Generated by Django 5.2.4 on 2025-07-18 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comicon', '0016_remove_prenotazione_evento_prenotazione_firmacopie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fumetto',
            name='genere',
            field=models.CharField(choices=[('azione', 'Azione'), ('avventura', 'Avventura'), ('fantasy', 'Fantasy'), ('horror', 'Horror'), ('commedia', 'Commedia'), ('drammatico', 'Drammatico'), ('storico', 'Storico'), ('altro', 'Altro')], default='altro', max_length=100),
        ),
    ]
