# Generated by Django 5.2.4 on 2025-10-13 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comicon', '0017_alter_fumetto_genere'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autore',
            name='casa_editrice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autori', to='comicon.casaeditrice'),
        ),
    ]
