# Generated by Django 5.2.4 on 2025-10-13 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comicon', '0018_alter_autore_casa_editrice'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='autore',
            constraint=models.UniqueConstraint(fields=('utente',), name='unique_autore_utente'),
        ),
    ]
