# Generated by Django 5.2.4 on 2025-10-13 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comicon', '0019_autore_unique_autore_utente'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='autore',
            name='unique_autore_utente',
        ),
        migrations.AlterField(
            model_name='autore',
            name='casa_editrice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comicon.casaeditrice'),
        ),
    ]
