# Generated by Django 5.2.4 on 2025-10-13 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comicon', '0020_remove_autore_unique_autore_utente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recensione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testo', models.TextField(max_length=1000)),
                ('voto', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('firmacopie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comicon.firmacopie')),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('utente', 'firmacopie')},
            },
        ),
    ]
